
// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Generates a summarized comparison of different insurance options based on user needs.
 *
 * - generateInsuranceSummary - A function that generates the insurance summary.
 * - InsuranceSummaryInput - The input type for the generateInsuranceSummary function.
 * - InsuranceSummaryOutput - The return type for the generateInsuranceSummary function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const InsuranceSummaryInputSchema = z.object({
  needs: z.string().describe('The specific insurance needs of the user.'),
  plans: z.string().describe('A description of the available insurance plans.'),
});

export type InsuranceSummaryInput = z.infer<typeof InsuranceSummaryInputSchema>;

const InsuranceSummaryOutputSchema = z.object({
  summary: z.string().describe('A summarized comparison of the insurance options.'),
});

export type InsuranceSummaryOutput = z.infer<typeof InsuranceSummaryOutputSchema>;

export async function generateInsuranceSummary(input: InsuranceSummaryInput): Promise<InsuranceSummaryOutput> {
  return insuranceSummaryFlow(input);
}

const prompt = ai.definePrompt({
  name: 'insuranceSummaryPrompt',
  input: {schema: InsuranceSummaryInputSchema},
  output: {schema: InsuranceSummaryOutputSchema},
  prompt: `بناءً على احتياجات المستخدم: {{{needs}}}، وخطط التأمين التالية: {{{plans}}}، قدم مقارنة موجزة لخيارات التأمين حتى يتمكن المستخدم من فهم الاختلافات بسهولة واتخاذ قرار مستنير.`,
});

const insuranceSummaryFlow = ai.defineFlow(
  {
    name: 'insuranceSummaryFlow',
    inputSchema: InsuranceSummaryInputSchema,
    outputSchema: InsuranceSummaryOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
